# Generated by Django 6.1.1 on 2026-09-28 15:17

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Scenario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Nazwa scenariusza")),
                (
                    "location",
                    models.CharField(
                        default="Katowice, Poland", max_length=100, verbose_name="Lokalizacja"
                    ),
                ),
                (
                    "latitude",
                    models.FloatField(default=50.2649, verbose_name="Szerokość geograficzna"),
                ),
                (
                    "longitude",
                    models.FloatField(default=19.0238, verbose_name="Długość geograficzna"),
                ),
                (
                    "residents_count",
                    models.IntegerField(default=4, verbose_name="Liczba mieszkańców"),
                ),
                ("description", models.TextField(blank=True, verbose_name="Opis")),
            ],
        ),
        migrations.CreateModel(
            name="PVSimulationConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("kwp", models.DecimalField(decimal_places=2, max_digits=5)),
                ("battery_kwh", models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ("annual_production_kwh", models.FloatField()),
                ("coverage_a_percent", models.FloatField()),
                ("coverage_b_percent", models.FloatField()),
                ("savings_a_eur", models.FloatField()),
                ("savings_b_eur", models.FloatField()),
                ("payback_a_years", models.FloatField(blank=True, null=True)),
                ("payback_b_years", models.FloatField(blank=True, null=True)),
                (
                    "scenario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pv_simulations",
                        to="energy.scenario",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HourlyEnergyRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("timestamp", models.DateTimeField(db_index=True, verbose_name="Data i Godzina")),
                (
                    "is_forecast",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="Czy to prognoza?"
                    ),
                ),
                (
                    "temperature",
                    models.FloatField(blank=True, null=True, verbose_name="Temperatura [°C]"),
                ),
                (
                    "solar_radiation",
                    models.FloatField(blank=True, null=True, verbose_name="Promieniowanie [W/m²]"),
                ),
                ("base_kwh", models.DecimalField(decimal_places=3, default=0.0, max_digits=6)),
                ("heating_kwh", models.DecimalField(decimal_places=3, default=0.0, max_digits=6)),
                ("lighting_kwh", models.DecimalField(decimal_places=3, default=0.0, max_digits=6)),
                ("cooking_kwh", models.DecimalField(decimal_places=3, default=0.0, max_digits=6)),
                (
                    "multimedia_kwh",
                    models.DecimalField(decimal_places=3, default=0.0, max_digits=6),
                ),
                (
                    "appliances_kwh",
                    models.DecimalField(decimal_places=3, default=0.0, max_digits=6),
                ),
                ("special_kwh", models.DecimalField(decimal_places=3, default=0.0, max_digits=6)),
                ("total_kwh", models.DecimalField(decimal_places=3, max_digits=7)),
                ("events", models.CharField(blank=True, default="", max_length=255)),
                (
                    "scenario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="energy_records",
                        to="energy.scenario",
                    ),
                ),
            ],
            options={
                "ordering": ["timestamp"],
                "indexes": [
                    models.Index(
                        fields=["scenario", "timestamp"], name="energy_hour_scenari_86454d_idx"
                    ),
                    models.Index(
                        fields=["is_forecast", "timestamp"], name="energy_hour_is_fore_6a1545_idx"
                    ),
                ],
            },
        ),
    ]
